source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'App_Example', :exclusive => true do
  pod "App", :path => "../"
end

target 'App_Tests', :exclusive => true do
  pod "App", :path => "../"

  
end
